### PR TITLE
Added arrow key navigation

### LINKED ISSUE #13: Use arrow keys to toggle colors
User should be able to toggle between different colors using left and right arrow keys. 

image

Some other key shortcuts have already been implemented.   Reference: https://github.com/gyanl/ChromaGen/issues/11  
[CONTRIBUTING.md](https://github.com/gyanl/ChromaGen/blob/gh-pages/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by sabinmarcu**
Fixes #13 

Takes into account not moving right when there's nothing left, while going left while at 0 will generate a new item. Can patch so that it doesn't generate a new color. 

Hope you like it (not much to it, really) :smile:

### CODE REVIEW

**Comment by gyanl** [comment]
Hey @sabinmarcu : Sorry for the late response, but we managed to get 4 PRs for the same issue, and it took me a while to review all of the code. We went with https://github.com/gyanl/ChromaGen/pull/16 since it addressed a bug with the keyboard copying shortcut as well. Thanks for your help! 

P.S. If you were doing this as part of Hacktoberfest, it'll still count as one PR. Thanks again!

**Comment by sabinmarcu** [comment]
Hi @gyanl . No worries, I'm glad your bug count is smaller now. 

Can I ask for a small favor? I'm not 100% sure how the hacktoberfest counting will go, so could you add the hacktoberfest label to the PR, just for good measure? 😄

**Comment by manu-chroma** [comment]
@sabinmarcu congrats! 
https://hacktoberfestchecker.herokuapp.com/?username=sabinmarcu

**Comment by manu-chroma** [comment]
also, tags don't actually matter but i've added one "just for good measure" :smile:

**Pull request closed without merging**
